package com.entity;

import java.io.Serializable;
import java.util.Set;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "apps_register")
public class AppRegister implements Serializable {

	private static final long serialVersionUID = 1L;
	private String Id;
	private String category;
	private String country;
	private String packName;
	private String timestamp;
	private String timezone;
	private String paidfree;
	private Boolean inAppPurchase;
	private Set<String> sdks;
	private String platform;
	private String organization;
	private String latestVersion;

	public AppRegister() {

	}

	public AppRegister(String category, String country, String packName,
			String timestamp, String timezone, String paidfree,
			Boolean inAppPurchase, Set<String> sdks, String platform,
			String organization, String latestVersion) {
		this.category = category;
		this.country = country;
		this.packName = packName;
		this.timestamp = timestamp;
		this.timezone = timezone;
		this.paidfree = paidfree;
		this.inAppPurchase = inAppPurchase;
		this.sdks = sdks;
		this.platform = platform;
		this.organization = organization;
		this.latestVersion = latestVersion;

	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "appId")
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName = "category")
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@DynamoDBAttribute(attributeName = "country")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@DynamoDBAttribute(attributeName = "packageName")
	public String getPackName() {
		return packName;
	}

	public void setPackName(String packName) {
		this.packName = packName;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "timestamp")
	public String getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@DynamoDBAttribute(attributeName = "timezone")
	public String getTimezone() {
		return timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@DynamoDBAttribute(attributeName = "paidfree")
	public String getPaidfree() {
		return paidfree;
	}

	public void setPaidfree(String paidfree) {
		this.paidfree = paidfree;
	}

	@DynamoDBAttribute(attributeName = "in_app_purchases")
	public Boolean getInAppPurchase() {
		return inAppPurchase;
	}

	public void setInAppPurchase(Boolean inAppPurchase) {
		this.inAppPurchase = inAppPurchase;
	}

	@DynamoDBAttribute(attributeName = "sdks")
	public Set<String> getSdks() {
		return sdks;
	}

	public void setSdks(Set<String> sdks) {
		this.sdks = sdks;
	}

	@DynamoDBAttribute(attributeName = "platform")
	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@DynamoDBAttribute(attributeName = "organization")
	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@DynamoDBAttribute(attributeName = "latest_version")
	public String getLatestVersion() {
		return latestVersion;
	}

	public void setLatestVersion(String latestVersion) {
		this.latestVersion = latestVersion;
	}

}
