package com.entity;

import java.io.Serializable;
import java.sql.Date;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "apps_users")
public class AppUsers implements Serializable {

	private static final long serialVersionUID = 1L;
	private String Id;
	private String country;
	private String city;
	private String deviceId;
	private String timestamp;
	private String lastSession;
	private String totalSessionCount;
	private String durationOfLastSession;
	private String carrier;
	private String platform;
	private String os;
	private Set<String> versionList;
	private String buildId;
	private String accessToken;

	public AppUsers() {

	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName = "country")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@DynamoDBAttribute(attributeName = "city")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@DynamoDBAttribute(attributeName = "timestamp")
	public String getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@DynamoDBAttribute(attributeName = "last_session")
	public String getLastSession() {
		return lastSession;
	}

	public void setLastSession(String lastSession) {
		this.lastSession = lastSession;
	}

	@DynamoDBAttribute(attributeName = "total_session_count")
	public String getTotalSessionCount() {
		return totalSessionCount;
	}

	public void setTotalSessionCount(String totalSessionCount) {
		this.totalSessionCount = totalSessionCount;
	}

	@DynamoDBAttribute(attributeName = "duration_of_last_session")
	public String getDurationOfLastSession() {
		return durationOfLastSession;
	}

	public void setDurationOfLastSession(String durationOfLastSession) {
		this.durationOfLastSession = durationOfLastSession;
	}

	@DynamoDBAttribute(attributeName = "carrier")
	public String getCarrier() {
		return carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	@DynamoDBAttribute(attributeName = "platform")
	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@DynamoDBAttribute(attributeName = "os")
	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@DynamoDBAttribute(attributeName = "version_list")
	public Set<String> getVersionList() {
		return versionList;
	}

	public void setVersionList(Set<String> versionList) {
		this.versionList = versionList;
	}

	@DynamoDBAttribute(attributeName = "build_id")
	public String getBuildId() {
		return buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	@DynamoDBRangeKey(attributeName = "access_token")
	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@DynamoDBAttribute(attributeName = "device_id")
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

}
